[app]
default_page_size = 10
jwt_secret = "123456"
log_path = "storage/logs"
log_file = "app.log"

[server]
run_mode = "debug"
port = "8080"
read_timeout = "60s"
write_timeout = "60s"

[database]
    [database.mysql]
    user = "k1"
    password = "123"
    host = "127.0.0.1"
    port = "3306"
    dbname = "blog"
    table_prefix = "blog_"
    max_idle_conns = 10
    max_open_conns = 30
